eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://naming-server:8761/eureka/
  instance:
    hostname: localhost
category:
  service:
    url: http://categorization-service:9091/categories/getCategory/{transactionType}
transaction:
  service:
    url: https://o5mpc77fx0.execute-api.eu-west-2.amazonaws.com/default/showcase-assignment-transactions-service
    endpoint:
      key: LdqTdyITMo14dKNtjehdO4JhiXYpHV9U9qz5Xtp3    
